### ISSUE TITLE
respect property precedence defined by maven

### ISSUE THREAD

**Issue by torsten-liermann** [release-engineering/pom-manipulation-ext#381] opened 2016-06-08 13:35 UTC
thanks for the great extension, but we encountered a behaviour that does not seem correct:
properties defined in pme.properties should not take presendence over properties defined via settings.xml or maven command line or system.
this hinders our development process because we would like to set the default to `false` for our developers and only active this extension in the ci-build.

thanks again!

**Comment by jdcasey** [comment] 2016-06-08 21:02
I'd tend to agree, it's the convention with Maven (and most other CLI tools I can think of) to respect CLI args over config files.

**Comment by rnc** [comment] 2016-06-09 08:54
I would concur. It was originally by design ( as in, it was a request for this pattern ). What I propose is that we change it to the more intuitive CLI overriding properties and add a flag to be able to invert it on demand.

**Comment by rnc** [comment] 2016-06-09 09:53
Fixed by #385

**Closed by rnc** 2016-06-09 09:53 UTC
