### ISSUE TITLE
alphanumeric suffixes are inconsistently split

### ISSUE THREAD

**Issue by lalmeras** [release-engineering/pom-manipulation-ext#446] opened 2017-01-11 15:29 UTC
Hi,

I notice what I considerer as an insistent behavior. Alphanumeric suffix (like -Dversion.suffix=jdk7) are splitted during pom manipulation, so that 0.12-SNAPSHOT is rewritten artifactId-0.12-jdk-7-SNAPSHOT.
I also notice that suffixes that includes an hyphen are not splitted. -Dversion.suffix=jdk7-bindgen rewrite previous example as 0.12-jdk7-bindgen-SNAPSHOT. This is the behavior that complies to my need.

Do you consider this as a bug, or is there a justification for it.

**Comment by rnc** [comment] 2017-01-12 21:56
I can reproduce this. It doesn't seem to matter whether the item is a SNAPSHOT or not. Workaround is to use `-Dversion.override=0.12-jdk7`
@pgier I would say the build number should not be split off in this scenario - what do you think? I think its the regex in Version?

**Comment by lalmeras** [comment] 2017-01-12 22:05
Thanks for this quick feedback. I just try the proposed workaround, but it seems that version.override suffers the same problem. With a version.override=0.12-jdk7, rewritten version is 0.12-jdk-7.

**Comment by rnc** [comment] 2017-01-12 23:11
Can you give me your version and full command line please?

**Comment by lalmeras** [comment] 2017-01-13 01:13
Error on my side, I do my test with version.override= on command line, but version.suffix still in pme.properties.

I use maven 3.3.9 / pom-manipulation-extension 2.6.
I initiate a simple pom project here : https://github.com/lalmeras/pom-manipulation-ext-test
pme.properties comments contain the results and I notice the following :

* version.override works just fine
* if version ends with a number and is not a snapshot (?), suffix separator is '.' (dot)
* if version ends with -SNAPSHOT or a letter (?), suffix separator is '-' (hyphen)

So I confirm the original issue and cancel my remark about version.override= because it just works fine.
But I think it is weird that the version / suffix separator changes based on version format.

**Comment by rnc** [comment] 2017-01-13 07:25
Thanks for the test code ; I didn't realise you had also enabled `version.osgi` and `version.suffix.snapshot` ; I suspect the interaction between these two may affect your last two points.

**Comment by lalmeras** [comment] 2017-01-13 08:37
No, I suppose that version.osgi=false *disable* osgi ?

**Comment by pgier** [comment] 2017-01-13 21:43
The current behaviour was sort of intentional due to trying to interpret the last number of a qualifier as a build number, and then formatting the qualifier appropriately.  However, I think the use case described here is valid and should be handled better.  I submitted a fix in PR #449.  I did have to make a minor change to one of the existing tests due to the conflicting behaviour, but I think the new way makes more sense.

**Comment by rnc** [comment] 2017-01-14 08:28
@pgier  - Nice - thanks for that! :-)

@lalmeras I've merged Paul's pull request if you want to give it a go.

**Comment by lalmeras** [comment] 2017-01-14 13:21
I confirm that the PR #449 resolves the suffix split I originally report. Thanks for this very quick workaround, support and fix.

But the second inconsistency I report (separator is '-' when version ends with a letter or is a SNAPHOST, '.' else) is still here. I don't know if you consider this as a bug.

Examples (still based on my test project):
* version 0.12 version.suffix=jdk7 → 0.12.jdk7 (version.suffix.snapshot has no impact)
* version 0.12-SNAPSHOT version.suffix=jdk7 → 0.12-jdk7-SNAPSHOT with version.suffix.snapshot=true, 0.12-jdk7 with version.suffix.snapshot=false
* version 0.12.A version.suffix=jdk7 → 0.12.A-jdk7 (version.suffix.snapshot has no impact)

Note: I do all my tests with version.osgi=false

**Comment by pgier** [comment] 2017-01-14 22:55
I think the behaviour that we want is to use a '.' when separating the version numbers and a '-' when separating the parts of the qualifier.  So the one that's currently incorrect is "0.12-jdk7" and "0.12-jdk7-SNAPSHOT".  These should be "0.12.jdk7" and "0.12.jdk7-SNAPSHOT".  @rnc what do you think?  Since we normally always use "osgi=true", I guess we don't run into these cases.

**Comment by lalmeras** [comment] 2017-01-15 10:35
So if I understand, if version ends with letters, you consider it is the first part of a qualifier, so you append the suffix (that is the last part of the qualifier) with '-'. Else, you append with '.' (as suffix is the whole qualifier)

So I agree that SNAPSHOT rewriting should be handled differently because SNAPSHOT is not the first part of a qualifier, and separator should be chosen based on the SNAPSHOT-less version number.

I re-read https://release-engineering.github.io/pom-manipulation-ext/guide/project-version-manip.html and I notice that all you said is effectively consistent with the documented behavior.

**Comment by rnc** [comment] 2017-01-16 12:04
@pgier @lalmeras Too many combinations :-)  


| version       | osgi  | suffix.snapshot | result |
| --------      | ----- | --------------- | ------ |
| 0.12-SNAPSHOT | false | true            | 0.12-jdk7-SNAPSHOT |
| 0.12-SNAPSHOT | true  | true            | 0.12.0.jdk7-SNAPSHOT |
| 0.12-SNAPSHOT | false | false           | 0.12-jdk7 |
| 0.12-SNAPSHOT | true  | false           | 0.12.0.jdk7 |


Next try a non snapshot source.

| version  | osgi  | suffix.snapshot | result |
| -------- | ----- | --------------- | ------ |
| 0.12     | true  | true            | 0.12.0.jdk7 |
| 0.12     | true  | false _Snapshot suffix has no effect_ | 0.12.0.jdk7 |
| 0.12     | false | true            | 0.12.jdk7 |

Next try with a snapshot with a build number (jdk-7)

| version       | osgi  | suffix.snapshot | result |
| --------      | ----- | --------------- | ------ |
| 0.12-SNAPSHOT | false | true            | 0.12-jdk-7-SNAPSHOT |
| 0.12-SNAPSHOT | true  | true            | 0.12.0.jdk-7-SNAPSHOT |
| 0.12-SNAPSHOT | false | false           | 0.12-jdk-7 |
| 0.12-SNAPSHOT | true  | false           | 0.12.0.jdk-7 |

| version  | osgi  | suffix.snapshot | result |
| -------- | ----- | --------------- | ------ |
| 0.12     | true  | true            | 0.12.0.jdk-7 |
| 0.12     | true  | false _Snapshot suffix has no effect_ | 0.12.0.jdk-7 |
| 0.12     | false | true            | 0.12.jdk-7 |


So, as Paul says, because we tend to use `version.osgi=true` we have not seen this. @pgier I agree - the 0.12-jdk-7 is not consistent with the delimeter used in the non-snapshot case ( `0.12.jdk-7` ). However, given version.osgi is false what should the delimiter and formatting be? If '.', we should at least make the scenarios consistent?

**Comment by pgier** [comment] 2017-01-16 22:47
Ok, I did some refactoring to make the parsing a bit simpler and hopefully fixed the remaining inconsistencies in pr #452

**Comment by rnc** [comment] 2017-01-17 13:34
@lalmeras Can you check this fixes your use-cases please?

**Comment by lalmeras** [comment] 2017-01-18 01:06
The last commit still fixes the original issue (numeric character is not split) and fix the inconsistencies for SNAPSHOT versions.

Currently, I obtain:
* version 0.12 version.suffix=jdk7 → 0.12.jdk7
* version 0.12-SNAPSHOT version.suffix=jdk7 → 0.12.jdk7-SNAPSHOT
* version 0.12.A version.suffix=jdk7 → 0.12.A-jdk7

These results are consistent with the behaviour explained by @pgier ('.' separator when suffix is the whole qualifier, '-' separator when version already contains a .textual qualifier) and I considerer my issue fixed.

Thanks @pgier and @rnc for your job

**Closed** 2017-01-18 10:14 UTC

**Comment by pgier** [comment] 2017-01-18 14:55
@lalmeras Thanks for finding and testing this!
