### ISSUE TITLE
repo-removal should push repos to a settings.xml file

### ISSUE THREAD

**Issue by jdcasey** [release-engineering/pom-manipulation-ext#172] opened 2015-07-28 15:52 UTC
When we remove repositories from the POM, we lose some information about where the project intended people to look for the artifacts it depends on. This may seem obvious, but in build environments it can be useful to have some alternative way of retrieving that info (something other than the POM, something that isn't published like the POM is).

We should generate / update a maven settings.xml in the project root with a profile that contains the repos that were removed when PME ran. I'd suggest making the name of this settings.xml file configurable, to maximize the ability to integrate with other build tooling.

**NOTE:** This will not be all that valuable to the build itself when running PME as a Maven extension, but will still provide documentation for what was removed...which could be committed / harvested later. For PME command-line invocations, the settings.xml could be committed and used during the build later.

**Comment by VaclavDedik** [comment] 2015-09-02 08:44
Question is what name (id) to choose for the profiles generated in the maven settings.xml. For the main repositories/reporting in the pom.xml file (i.e. those that are not nested in a profile), we can choose something like "removed-by-pme" or make it configurable. The problem is with repositories nested in a profile, we probably shouldn't include them in the same profile (e.g. "removed-by-pme"), so we have to choose a different id. The obvious id would be the same id as the id of the profile in the pom.xml. Another option is to choose the same id but add a suffix to it. Probably going to choose the former (for now).

**Comment by rnc** [comment] 2015-09-03 09:08
Fixed by #201

**Closed by rnc** 2015-09-03 09:08 UTC
Labels: enhancement
